// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartWMS.Infrastructure.Persistence;

#nullable disable

namespace SmartWMS.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("CurrentOccupancy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("MaxCapacity")
                        .HasColumnType("float");

                    b.Property<Guid>("ZoneId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ZoneId");

                    b.ToTable("Bins");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c1000000-0000-0000-0000-000000000001"),
                            Code = "C-Z1-R1-L1",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SystemAdmin",
                            CurrentOccupancy = 0.0,
                            MaxCapacity = 100.0,
                            ZoneId = new Guid("f2e96440-1996-4e5b-9d41-3b7c0604b087")
                        },
                        new
                        {
                            Id = new Guid("c1000000-0000-0000-0000-000000000002"),
                            Code = "C-Z1-R2-L1",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SystemAdmin",
                            CurrentOccupancy = 0.0,
                            MaxCapacity = 100.0,
                            ZoneId = new Guid("f2e96440-1996-4e5b-9d41-3b7c0604b087")
                        },
                        new
                        {
                            Id = new Guid("c1000000-0000-0000-0000-000000000003"),
                            Code = "C-Z1-R3-L1",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SystemAdmin",
                            CurrentOccupancy = 0.0,
                            MaxCapacity = 100.0,
                            ZoneId = new Guid("f2e96440-1996-4e5b-9d41-3b7c0604b087")
                        },
                        new
                        {
                            Id = new Guid("c1000000-0000-0000-0000-000000000004"),
                            Code = "C-Z1-R4-L1",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SystemAdmin",
                            CurrentOccupancy = 0.0,
                            MaxCapacity = 100.0,
                            ZoneId = new Guid("f2e96440-1996-4e5b-9d41-3b7c0604b087")
                        },
                        new
                        {
                            Id = new Guid("c1000000-0000-0000-0000-000000000005"),
                            Code = "C-Z1-R5-L1",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SystemAdmin",
                            CurrentOccupancy = 0.0,
                            MaxCapacity = 100.0,
                            ZoneId = new Guid("f2e96440-1996-4e5b-9d41-3b7c0604b087")
                        },
                        new
                        {
                            Id = new Guid("d2000000-0000-0000-0000-000000000001"),
                            Code = "D-Z2-R1-L1",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SystemAdmin",
                            CurrentOccupancy = 0.0,
                            MaxCapacity = 500.0,
                            ZoneId = new Guid("e84988e0-087e-40f4-904d-771804d9c02a")
                        },
                        new
                        {
                            Id = new Guid("d2000000-0000-0000-0000-000000000002"),
                            Code = "D-Z2-R2-L1",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SystemAdmin",
                            CurrentOccupancy = 0.0,
                            MaxCapacity = 500.0,
                            ZoneId = new Guid("e84988e0-087e-40f4-904d-771804d9c02a")
                        },
                        new
                        {
                            Id = new Guid("d2000000-0000-0000-0000-000000000003"),
                            Code = "D-Z2-R3-L1",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SystemAdmin",
                            CurrentOccupancy = 0.0,
                            MaxCapacity = 500.0,
                            ZoneId = new Guid("e84988e0-087e-40f4-904d-771804d9c02a")
                        },
                        new
                        {
                            Id = new Guid("d2000000-0000-0000-0000-000000000004"),
                            Code = "D-Z2-R4-L1",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SystemAdmin",
                            CurrentOccupancy = 0.0,
                            MaxCapacity = 500.0,
                            ZoneId = new Guid("e84988e0-087e-40f4-904d-771804d9c02a")
                        },
                        new
                        {
                            Id = new Guid("d2000000-0000-0000-0000-000000000005"),
                            Code = "D-Z2-R5-L1",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SystemAdmin",
                            CurrentOccupancy = 0.0,
                            MaxCapacity = 500.0,
                            ZoneId = new Guid("e84988e0-087e-40f4-904d-771804d9c02a")
                        });
                });

            modelBuilder.Entity("SmartWMS.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Unit")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Barcode")
                        .IsUnique();

                    b.HasIndex("SKU")
                        .IsUnique();

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Warehouse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Warehouses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7a9089f2-2b22-4211-912b-28562d2925a1"),
                            Address = "Khu Công Nghệ Cao, Quận 9, TP. Thủ Đức",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SystemAdmin",
                            Name = "Kho Tổng Thông Minh - SmartWMS Center"
                        });
                });

            modelBuilder.Entity("Zone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WarehouseId");

                    b.ToTable("Zones");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f2e96440-1996-4e5b-9d41-3b7c0604b087"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SystemAdmin",
                            Name = "Khu Mát (Cold Zone)",
                            WarehouseId = new Guid("7a9089f2-2b22-4211-912b-28562d2925a1")
                        },
                        new
                        {
                            Id = new Guid("e84988e0-087e-40f4-904d-771804d9c02a"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SystemAdmin",
                            Name = "Khu Khô (Dry Zone)",
                            WarehouseId = new Guid("7a9089f2-2b22-4211-912b-28562d2925a1")
                        });
                });

            modelBuilder.Entity("Bin", b =>
                {
                    b.HasOne("Zone", "Zone")
                        .WithMany("Bins")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("Zone", b =>
                {
                    b.HasOne("Warehouse", "Warehouse")
                        .WithMany("Zones")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Warehouse", b =>
                {
                    b.Navigation("Zones");
                });

            modelBuilder.Entity("Zone", b =>
                {
                    b.Navigation("Bins");
                });
#pragma warning restore 612, 618
        }
    }
}
